LGTMProjectURLs:
    ApplicationCode: https://lgtm.com/projects/g/giusepperaffa/si-tool-application-test/
    InfrastructureCode: https://lgtm.com/projects/g/giusepperaffa/si-tool-infrastructure-test/
